### ISSUE TITLE
Failed to import the site module

### ISSUE THREAD

**Issue by carmine-paolino-olx** [guildai/guildai#11]
Hi,

I'm running Python 3.6.4 installed from Homebrew on Mac OS X High Sierra.

While trying the MNIST tutorial I stumbled upon the following issue:

At training time, both the softmax and the CNN version of the models return the following error:

```
$ guild train mnist-cnn
You are about to run mnist/mnist-cnn:train
  batch-size: 100
  epochs: 10
Continue? (Y/n)
Resolving mnist/dataset dependency
Using cached file /Users/carmine.paolino/.guild/cache/resources/d5c519b6566ca19e5ba3d3df4d026508a2197b7537ff421a117dc3b2/train-images-idx3-ubyte.gz
Using cached file /Users/carmine.paolino/.guild/cache/resources/5980b7fde40f5c0394c72d940cb6d4e8640d39aa0361c3da5134541b/train-labels-idx1-ubyte.gz
Using cached file /Users/carmine.paolino/.guild/cache/resources/7d81ab64becd5afde3d50ac5776e6598d9944f4cd0beeaa1e4647b7b/t10k-images-idx3-ubyte.gz
Using cached file /Users/carmine.paolino/.guild/cache/resources/9dc7919e93cf5fade761b0a130485a22362fa321fc435abe01718946/t10k-labels-idx1-ubyte.gz
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 580, in get_config_vars
    import _osx_support
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by gar1t** [comment]
@carmine-paolino-olx this SO thread seems to address the same issue:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

The suggested resolution is to uninstall `enum34`:

    pip uninstall enum34

There's also another possible solution, which is to unset the `PYTHONPATH` env var:

    unset PYTHONPATH

Out of curiosity, are you able to start the Python repl or run any other Python commands using 3.6.4?

**Comment by cfregly** [comment]
related to https://github.com/guildai/guild/issues/4

**Comment by gar1t** [comment]
Closing this as we haven't seen reports of this for quite a while.
