### ISSUE TITLE
Failing When Building Within Docker Image

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#12]
My Dockerfile is here:
```
FROM pipelineai/ubuntu-16.04-cpu:1.5.0

WORKDIR /root

RUN \
  apt-get update \
  && apt-get install -y build-essential \
  && apt-get install -y npm nodejs nodejs-legacy wget locales git \
  && apt-get clean

# libav-tools for matplotlib anim
RUN \
  apt-get install -y --no-install-recommends libav-tools \
  && apt-get clean

# Install JupyterHub dependencies
RUN \
  npm install -g configurable-http-proxy && rm -rf ~/.npm

RUN \
  mkdir -p /root/logs

ENV \
  LOGS_HOME=/root/logs

COPY sysutils/ sysutils/

RUN \
  pip install --upgrade pip

ENV \
  PIPELINE_CLI_VERSION=1.5.101

RUN \
  pip install cli-pipeline==${PIPELINE_CLI_VERSION}

COPY guild-0.3.1.rc1/ guild/
#RUN \
#  rm -rf guild/build/ || true \
#  && rm -rf guild/dist || true \
#  && rm -rf guild/external || true \
#  && rm -rf guild/view/node_modules || true

#RUN \
#  apt-get install -y python-setuptools python3-setuptools

RUN \
  cd guild \
  && pip install -r requirements.txt

RUN \
  pip list

RUN \
  cd guild \
  && python setup.py build
```

```
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3

> guildai-view@1.0.0 build /root/guild/guild/view
> node build/build.js

/root/guild/guild/view/build/webpack.base.conf.js:32
      ...(config.dev.useEslint? [{
      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/guild/guild/view/build/webpack.prod.conf.js:7:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! guildai-view@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the guildai-view@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the guildai-view package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs guildai-view
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls guildai-view
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/guild/guild/view/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 202, in <module>
    zip_safe=False,
  File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 82, in run
    _build_view_dist()
  File "setup.py", line 145, in _build_view_dist
    subprocess.check_call(["npm", "run", "build"], cwd="./guild/view")
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1.
```

**Comment by gar1t** [comment]
The version of Node JS that you're using is a bit dated and doesn't support the spread syntax:

```
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
```

I'll update the docs to require at least Node JS 8.5.0.

**Comment by cfregly** [comment]
good to know.  this works on my macbook, but i do everything for productionwithin 16.04 ubuntu docker images.

that’s why i sometimes don’t see stuff for a few days.

i will override the default nodejs install from ubuntu to get to the version you specified.

**Comment by gar1t** [comment]
FYI, there is no stable branch for Guild atm, so building source is risky business. Is there a particular reason you're not installing the package? These are all vetted with reasonably solid test coverage before going up to PyPI.

**Comment by cfregly** [comment]
Here is my solution.
```
  apt-get install -y build-essential \
  && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
  && apt-get install -y nodejs
```

**Comment by cfregly** [comment]
@gar1t  re: your comment, "Is there a particular reason you're not installing the package? These are all vetted with reasonably solid test coverage before going up to PyPI."

remember that others may want to contribute back to this project.  if they can't build the project, they can't test before contributing.

we're developers - we like things to build.  a dependency on a particular version of nodejs is certainly worth documenting.  help us help you!  :)

**Comment by gar1t** [comment]
@cfregly I'm certainly not challenging your right to build from source :) That's a first class use case! I wanted to know if there was a particular reason you weren't using the distributions on PyPI. If there was, I'd want to to make sure that was fixed.

Thanks for the report!
