### ISSUE TITLE
ImportError: cannot import name 'SharedDataMiddleware' from 'werkzeug.wsgi'

### ISSUE THREAD

**Issue by melgor** [guildai/guildai#134]
When running `guildai view` I get error:
```
Traceback (most recent call last):
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/bin/guild", line 10, in <module>
    sys.exit(main())
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/main_bootstrap.py", line 38, in main
    guild.main.main()
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/main.py", line 32, in main
    _main()
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/main.py", line 38, in _main
    main_cmd.main(standalone_mode=False)
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/external/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/external/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/external/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/external/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/external/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/click_util.py", line 146, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/commands/view.py", line 64, in view
    from . import view_impl
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/commands/view_impl.py", line 33, in <module>
    from guild import view
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/view.py", line 29, in <module>
    from guild import serving_util
  File "/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/guild/serving_util.py", line 26, in <module>
    from werkzeug.wsgi import SharedDataMiddleware
ImportError: cannot import name 'SharedDataMiddleware' from 'werkzeug.wsgi' (/home/bartosz.ludwiczuk/.conda/envs/mlearn/lib/python3.7/site-packages/werkzeug/wsgi.py)
```

In normal console it work properly:
![Screenshot 2020-03-02 at 12 58 47](https://user-images.githubusercontent.com/2587438/75674544-91846480-5c85-11ea-9208-0778f9a5bbfc.png)

Everything was run at GCP cloud.

**Comment by gar1t** [comment]
You're importing from the correct location as of Werkzeug 0.15 and above - but Guild is not. This is a bug in `0.6.6` since Werzkeug `1.0` was released (which breaks backward compatibility with that API).

You can fix this a couple ways:

- Install the latest pre-release of Guild using `pip install guildai --upgrade --pre`
- Downgrade to werkzeug 0.14 using `pip install werkzeug==0.14.1`
