### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pkg_type'

### ISSUE THREAD

**Issue by MartinPernus** [guildai/guildai#204]
Hi,

I'm using guild version 0.7.0.rc11.

When running `guild run <options>` with hyperparameter sweep, the first run runs fine. When the next run starts, the following error occurs:

`
Traceback (most recent call last): 
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_main.py", line 41, in <module>
    main()
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_main.py", line 26, in main
    batch_util.handle_trials(batch_run, trials)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_util.py", line 56, in handle_trials
    _run_trials(batch_run, trials)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_util.py", line 102, in _run_trials
    _start_trial_run(trial_run, stage)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_util.py", line 138, in _start_trial_run
    _log_start_trial(run, stage)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/batch_util.py", line 159, in _log_start_trial
    run_util.format_operation(run),
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/run_util.py", line 222, in format_operation
    base_desc = _base_op_desc(opref, nowarn)
  File "/home/user/.virtualenvs/venv/lib/python3.7/site-packages/guild/run_util.py", line 227, in _base_op_desc
    if opref.pkg_type == "guildfile":
AttributeError: 'NoneType' object has no attribute 'pkg_type'
`

**Comment by gar1t** [comment]
Thank you for the report - sorry you're facing this issue.

Is this something that you can reproduce with a minimal example?
