### ISSUE TITLE
Folder not copied to remote (--test-sourcecode lists it, however)

### ISSUE THREAD

**Issue by christabella** [guildai/guildai#229]
Hello! I have a weird little situation that only happens on a remote while local is fine, and tried to explain it as best as I could... [My guild file is here](https://github.com/christabella/meta_learning_pacoh/commit/7d288b66973a7bba6f5240dd1c7739b4a6a3ac78) and that repository should be a self-contained example.

When I do `--test-sourcecode` with `guild run 1D:train-np --remote fugue --test-sourcecode -y`, the entire `experiments/` folder is selected for copy.

![image](https://user-images.githubusercontent.com/2038751/91937440-92f91d00-ecfa-11ea-8178-4a26bfd0c613.png)

However, when actully running it with `guild run 1D:train-np --remote fugue -y`, the folder does not seem to actually get copied over. When trying to verify it with `guild ls 1 --remote fugue --sourcecode`, I get an empty list, but I guess that's just because the run errored out (?):

![image](https://user-images.githubusercontent.com/2038751/91937647-0864ed80-ecfb-11ea-84e8-44c8c3cf1cbc.png)

The full stack trace from `guild run 1D:train-np --remote fugue -y`, which has no `experiments/` folder being copied, is:
```
Building package
package src: /Users/christabellairwanto/repos/meta_learning_pacoh
package dist: /var/folders/wp/q9lyg0h904n4whtwk89vp60c0000gn/T/guild-remote-stage-om18n8yk
running clean
removing 'build/lib' (and everything under it)
removing 'build/bdist.macosx-10.9-x86_64' (and everything under it)
'build/scripts-3.8' does not exist -- can't clean it
removing 'build'
running bdist_wheel
running build
running build_py
package init file '/Users/christabellairwanto/repos/meta_learning_pacoh/__init__.py' not found (or not a regular file)
creating build
creating build/lib
creating build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/config.py -> build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/setup.py -> build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/run_1D_experiments.py -> build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/demo.py -> build/lib/1D
creating build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/abstract.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_meta_mlap.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_meta_vi.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_meta_svgd.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/models.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/MAML.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/NPR_meta.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/util.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/random_gp.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/__init__.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_mll.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_pac.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/GPR_meta_mll.py -> build/lib/1D/meta_learn
copying /Users/christabellairwanto/repos/meta_learning_pacoh/meta_learn/svgd.py -> build/lib/1D/meta_learn
creating build/lib/1D/tests
copying /Users/christabellairwanto/repos/meta_learning_pacoh/tests/test_utils.py -> build/lib/1D/tests
copying /Users/christabellairwanto/repos/meta_learning_pacoh/tests/test_data_sim.py -> build/lib/1D/tests
copying /Users/christabellairwanto/repos/meta_learning_pacoh/tests/__init__.py -> build/lib/1D/tests
copying /Users/christabellairwanto/repos/meta_learning_pacoh/tests/test_GPR.py -> build/lib/1D/tests
creating build/lib/1D/third_party
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/__init__.py -> build/lib/1D/third_party
creating build/lib/1D/custom_tune
copying /Users/christabellairwanto/repos/meta_learning_pacoh/custom_tune/hyperopt_wrapper.py -> build/lib/1D/custom_tune
copying /Users/christabellairwanto/repos/meta_learning_pacoh/custom_tune/trial_runner.py -> build/lib/1D/custom_tune
copying /Users/christabellairwanto/repos/meta_learning_pacoh/custom_tune/__init__.py -> build/lib/1D/custom_tune
copying /Users/christabellairwanto/repos/meta_learning_pacoh/custom_tune/tune.py -> build/lib/1D/custom_tune
creating build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/main_experiment.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/models.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/datasets.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/__init__.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/neural_process.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/utils.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/third_party/neural_processes/training.py -> build/lib/1D/third_party/neural_processes
copying /Users/christabellairwanto/repos/meta_learning_pacoh/guild.yml -> build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/LICENSE -> build/lib/1D
copying /Users/christabellairwanto/repos/meta_learning_pacoh/README.md -> build/lib/1D
installing to build/bdist.macosx-10.9-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/wheel
creating build/bdist.macosx-10.9-x86_64/wheel/1D
copying build/lib/1D/guild.yml -> build/bdist.macosx-10.9-x86_64/wheel/1D
copying build/lib/1D/config.py -> build/bdist.macosx-10.9-x86_64/wheel/1D
copying build/lib/1D/LICENSE -> build/bdist.macosx-10.9-x86_64/wheel/1D
creating build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/abstract.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_meta_mlap.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_meta_vi.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_meta_svgd.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/models.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/MAML.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/NPR_meta.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/util.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/random_gp.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_mll.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_pac.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/GPR_meta_mll.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
copying build/lib/1D/meta_learn/svgd.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/meta_learn
creating build/bdist.macosx-10.9-x86_64/wheel/1D/tests
copying build/lib/1D/tests/test_utils.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/tests
copying build/lib/1D/tests/test_data_sim.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/tests
copying build/lib/1D/tests/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/tests
copying build/lib/1D/tests/test_GPR.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/tests
copying build/lib/1D/README.md -> build/bdist.macosx-10.9-x86_64/wheel/1D
copying build/lib/1D/setup.py -> build/bdist.macosx-10.9-x86_64/wheel/1D
creating build/bdist.macosx-10.9-x86_64/wheel/1D/third_party
copying build/lib/1D/third_party/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party
creating build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/main_experiment.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/models.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/datasets.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/neural_process.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/utils.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/third_party/neural_processes/training.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/third_party/neural_processes
copying build/lib/1D/run_1D_experiments.py -> build/bdist.macosx-10.9-x86_64/wheel/1D
copying build/lib/1D/demo.py -> build/bdist.macosx-10.9-x86_64/wheel/1D
creating build/bdist.macosx-10.9-x86_64/wheel/1D/custom_tune
copying build/lib/1D/custom_tune/hyperopt_wrapper.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/custom_tune
copying build/lib/1D/custom_tune/trial_runner.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/custom_tune
copying build/lib/1D/custom_tune/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/custom_tune
copying build/lib/1D/custom_tune/tune.py -> build/bdist.macosx-10.9-x86_64/wheel/1D/custom_tune
running install_egg_info
running egg_info
writing 1D.egg-info/PKG-INFO
writing dependency_links to 1D.egg-info/dependency_links.txt
writing entry points to 1D.egg-info/entry_points.txt
writing namespace_packages to 1D.egg-info/namespace_packages.txt
writing top-level names to 1D.egg-info/top_level.txt
reading manifest file '1D.egg-info/SOURCES.txt'
writing manifest file '1D.egg-info/SOURCES.txt'
Copying 1D.egg-info to build/bdist.macosx-10.9-x86_64/wheel/1D-0.0.0-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-10.9-x86_64/wheel/1D-0.0.0.dist-info/WHEEL
creating '/var/folders/wp/q9lyg0h904n4whtwk89vp60c0000gn/T/guild-remote-stage-om18n8yk/1D-0.0.0-py2.py3-none-any.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
adding '1D/LICENSE'
adding '1D/README.md'
adding '1D/config.py'
adding '1D/demo.py'
adding '1D/guild.yml'
adding '1D/run_1D_experiments.py'
adding '1D/setup.py'
adding '1D/custom_tune/__init__.py'
adding '1D/custom_tune/hyperopt_wrapper.py'
adding '1D/custom_tune/trial_runner.py'
adding '1D/custom_tune/tune.py'
adding '1D/meta_learn/GPR_meta_mlap.py'
adding '1D/meta_learn/GPR_meta_mll.py'
adding '1D/meta_learn/GPR_meta_svgd.py'
adding '1D/meta_learn/GPR_meta_vi.py'
adding '1D/meta_learn/GPR_mll.py'
adding '1D/meta_learn/GPR_pac.py'
adding '1D/meta_learn/MAML.py'
adding '1D/meta_learn/NPR_meta.py'
adding '1D/meta_learn/__init__.py'
adding '1D/meta_learn/abstract.py'
adding '1D/meta_learn/models.py'
adding '1D/meta_learn/random_gp.py'
adding '1D/meta_learn/svgd.py'
adding '1D/meta_learn/util.py'
adding '1D/tests/__init__.py'
adding '1D/tests/test_GPR.py'
adding '1D/tests/test_data_sim.py'
adding '1D/tests/test_utils.py'
adding '1D/third_party/__init__.py'
adding '1D/third_party/neural_processes/__init__.py'
adding '1D/third_party/neural_processes/datasets.py'
adding '1D/third_party/neural_processes/main_experiment.py'
adding '1D/third_party/neural_processes/models.py'
adding '1D/third_party/neural_processes/neural_process.py'
adding '1D/third_party/neural_processes/training.py'
adding '1D/third_party/neural_processes/utils.py'
adding '1D-0.0.0.dist-info/LICENSE'
adding '1D-0.0.0.dist-info/METADATA'
adding '1D-0.0.0.dist-info/PACKAGE'
adding '1D-0.0.0.dist-info/WHEEL'
adding '1D-0.0.0.dist-info/entry_points.txt'
adding '1D-0.0.0.dist-info/namespace_packages.txt'
adding '1D-0.0.0.dist-info/top_level.txt'
adding '1D-0.0.0.dist-info/RECORD'
removing build/bdist.macosx-10.9-x86_64/wheel
Initializing remote run
Copying package
building file list ... done
1D-0.0.0-py2.py3-none-any.whl

sent 89463 bytes  received 42 bytes  59670.00 bytes/sec
total size is 89334  speedup is 1.00
Installing package and its dependencies
Processing ./1D-0.0.0-py2.py3-none-any.whl
Installing collected packages: 1D
Successfully installed 1D-0.0.0
Starting 1D:train-np on fugue as 213265ece72c4868b425caf0e9e2818d
Running /m/home/home7/71/irwantc1/unix/.conda/envs/ANP_RNN_torch/.guild/runs/213265ece72c4868b425caf0e9e2818d/.guild/sourcecode/run_1D_experiments.py



Traceback (most recent call last):
  File "/m/home/home7/71/irwantc1/unix/.conda/envs/ANP_RNN_torch/.guild/runs/213265ece72c4868b425caf0e9e2818d/.guild/sourcecode/run_1D_experiments.py", line 126, in <module>
    main(args)
  File "/m/home/home7/71/irwantc1/unix/.conda/envs/ANP_RNN_torch/.guild/runs/213265ece72c4868b425caf0e9e2818d/.guild/sourcecode/run_1D_experiments.py", line 70, in main
    fit_eval_meta_algo(param_dict)
  File "/m/home/home7/71/irwantc1/unix/.conda/envs/ANP_RNN_torch/.guild/runs/213265ece72c4868b425caf0e9e2818d/.guild/sourcecode/run_1D_experiments.py", line 50, in fit_eval_meta_algo
    from experiments.data_sim import provide_data
ModuleNotFoundError: No module named 'experiments'
Run 213265ece72c4868b425caf0e9e2818d stopped with a status of 'error'
```

**Comment by gar1t** [comment]
Hi @christabella sorry for the late reply!

Guild does not yet use the source code spec when creating packages, which are used for remote runs. This will be resolved in an upcoming release.

Guild uses setuptools `find_packages` to locate applicable source code. It looks like `experiments` is acting as a Python package but is missing the `__init__.py` marker. If you add that file to `experiments` it should appear in the package and be available for remote runs.

The other topic to keep an eye for is non-package files - e.g. JSON, etc. For these you need to add entries to the `package` `data-files` attribute.

``` yaml
- package: my-package
  data-files:
    - config.json
    - data
```

In this example, the `config.json` file will be included in the package as well as the `data` directory.

This interface reflects rather transparently the interface used by setuptools. This is great if you're an expert in setuptools but a pain if you just want things to work given a `sourcecode` spec, which I think is quite reasonable! I'll bump this issue in priority so we resolve it for a near-term release.

**Comment by gar1t** [comment]
See also #231

**Comment by christabella** [comment]
Not late at all :) Thanks a lot, I learnt something new! Maybe I can close this since your `__init__.py` fix works like a charm, unless you want to keep it open until the `sourcecode` spec is used to create packages for remote runs?
