### ISSUE TITLE
Guild check error

### ISSUE THREAD

**Issue by MartinPernus** [guildai/guildai#235]
Hi,

I am trying to change the used python interpreter for 'guild run' operation. I have two questions:
- How do I change the python interpreter for 'guild run'? I must have messed up my setup since it doesn't seem to want to use the activated Python virtual environment, but instead uses the default system-level Python interpreter.

- When I try to check, what interpreter it's using, I get the following error
`$ guild check`

    guild_version:             0.7.0.post1
    guild_install_location:    /usr/local/lib/python3.7/dist-packages/guild
    guild_home:                mydir/myGAN/guild
    guild_resource_cache:      mydir/myGAN/guild/cache/resources
    Traceback (most recent call last):
      File "/usr/local/bin/guild", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.7/dist-packages/guild/main_bootstrap.py", line 40, in main
        guild.main.main()
      File "/usr/local/lib/python3.7/dist-packages/guild/main.py", line 33, in main
        _main()
      File "/usr/local/lib/python3.7/dist-packages/guild/main.py", line 40, in _main
        main_cmd.main(standalone_mode=False)
      File "/usr/local/lib/python3.7/dist-packages/guild/external/click/core.py", line 759, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/guild/external/click/core.py", line 714, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.7/dist-packages/guild/external/click/core.py", line 1132, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.7/dist-packages/guild/external/click/core.py", line 951, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.7/dist-packages/guild/external/click/core.py", line 552, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/guild/click_util.py", line 151, in fn
        return fn0(*(args + (Args(**kw),)))
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check.py", line 73, in check
        check_impl.main(args)
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check_impl.py", line 84, in main
        _check(args)
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check_impl.py", line 92, in _check
        _print_info(check)
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check_impl.py", line 125, in _print_info
        _print_guild_info()
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check_impl.py", line 148, in _print_guild_info
        cli.out("installed_plugins:         %s" % _format_plugins())
      File "/usr/local/lib/python3.7/dist-packages/guild/commands/check_impl.py", line 160, in _format_plugins
        return ", ".join([name for name, _ in sorted(plugin.iter_plugins())])
    TypeError: '<' not supported between instances of 'CPUPlugin' and 'CPUPlugin'

**Comment by gar1t** [comment]
Well that's annoying - sorry you're facing this. When you run `guild check` do you have an activated Python environment? If so what version of Python is that?

To ensure Guild is applicable to the activated Python environment, you can try installing it explicitly within the activated environment.

In the meantime, I spot a bug in the traceback you provided that I'll fix for the `check` command. But this will only get us a little further along.

To work around the issue of running your operations with a specific instance of Python, you can use the `exec` operation attribute:

``` yaml
op:
  exec: PATH_TO_PYTHON_EXE -um guild.op_main MAIN_SPEC -- ${flag_args}
``` 

Replace `PATH_TO_PYTHON_EXE` above with the full path to the Python interpreter you want to use. Replace `MAIN_SPEC` with what you have for `main`. Comment out `main` because we'll want to return to that once we figure out what's going on with the environment (which we need check for). This should at least get you moving forward without having to wait to solve the other parts.

**Comment by MartinPernus** [comment]
Hi,

I get the same error whether I have an activated virtual environment or not.

I like the idea of having the same virtual environment for similar projects, that's why I'm not too keen on installing another one. I will try the solution with exec operation.

**Comment by gar1t** [comment]
I'm not able to create this anymore with 0.7.2. I'm going to close. We can reopen as needed.
