### ISSUE TITLE
Bug: stopping a run that's being run by a queue freezes the queue

### ISSUE THREAD

**Issue by FelixAbrahamsson** [guildai/guildai#245]
When running an operation via guild queue that uses multiprocessing, the queue will hang if I stop the run with `guild runs stop <run>`. This does not happen if the operation runs on a single thread.

Using version `0.7.0.post1` of guild.

This is the stack trace
```
Traceback (most recent call last):  
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main                                                                                                                  
    return _run_code(code, main_globals, None,                                                                                                                                          
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code                                                                                                                             
    exec(code, run_globals)                                                                                                                                                             
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/main_bootstrap.py", line 70, in <module>                                                                
    main()                                                                                                                                                                              
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/main_bootstrap.py", line 40, in main                                                                    
    guild.main.main()                                                                                                                                                                   
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/main.py", line 33, in main                                                                              
    _main()                                                                                                                                                                             
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/main.py", line 40, in _main                                                                             
    main_cmd.main(standalone_mode=False)                                                                                                                                                
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/external/click/core.py", line 759, in __call__                                                          
    return self.main(*args, **kwargs)                                                                                                                                                   
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/external/click/core.py", line 714, in main                                                              
    rv = self.invoke(ctx)                                                                                  
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/external/click/core.py", line 1132, in invoke                             
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                             
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/external/click/core.py", line 951, in invoke                                                            
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                      
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/external/click/core.py", line 552, in invoke                                                            
    return callback(*args, **kwargs)                                                                                                                                                    
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/click_util.py", line 151, in fn                                                                         
    return fn0(*(args + (Args(**kw),)))                                                                                                                                                 
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run.py", line 457, in run                                                                      
    run_impl.main(args)                                                                                                                                                                 
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1296, in main                                                               
    _dispatch_op(S)                                                                                                                                                                     
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1380, in _dispatch_op                                                       
    _dispatch_op_cmd(S)                                                                                                                                                                 
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1567, in _dispatch_op_cmd                                                   
    _confirm_and_run(S)                                                                                                                                                                 
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1635, in _confirm_and_run                                                   
    _run(S)                                                                                                                                                                             
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1826, in _run                                                               
    _run_local(S)                                                                                                                                                                       
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1857, in _run_local                                                         
    _run_op(op, S.args)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/commands/run_impl.py", line 1960, in _run_op
    _, exit_status = oplib.run(
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 162, in run
    exit_status = _run_op(run, op, quiet, stop_after, extra_env)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 191, in _run_op
    exit_status = _op_wait_for_proc(op, proc, run, quiet, stop_after)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 242, in _op_wait_for_proc
    return _op_watch_proc(op, proc, run, quiet, stop_after)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 250, in _op_watch_proc
    return _proc_wait_with_run_output(proc, run, quiet, output_summary, stop_after)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 263, in _proc_wait_with_run_output
    return _proc_wait(proc, stop_after)
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op.py", line 280, in __exit__
    self._output.wait_and_close()
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op_util.py", line 365, in wait_and_close
    self.close()
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op_util.py", line 332, in close
    self._close()
  File "/home/ubuntu/code/shadow-removal/venv/lib/python3.8/site-packages/guild/op_util.py", line 354, in _close
    assert not self._out_tee.is_alive()
AssertionError
```

**Comment by gar1t** [comment]
Apologies for the late reply here!

No question this is an issue but with a simple example I'm not able to recreate this. 

When you say multiprocessing here, are you running multiple queues concurrently?

**Comment by FelixAbrahamsson** [comment]
Ah I was unclear, I meant the operation uses python multiprocessing! In this case pytorch data loaders with multiple workers

**Comment by gar1t** [comment]
Got it! This will be resolved in the next release (0.7.3). Thanks for the report!
