### ISSUE TITLE
Error with guild.yml but not guild run train.py

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#26]
I am using tensorflow 2.0a and `guild train.py` works fine for me. However, when i specify a guild.yml file and run `guild run train` it fails with the following error:

```
You are about to run clamp-detector:train
  batch_size: 2
  epochs: 2
  evaluation_batch_size: 32
  gradient_clipvalue: 1.0
  learning_rate: 0.001
  model_dir: runs/model
  oversample_factor: 15
  seed: 1000
  steps_per_epoch: 100
  validation_split_seed: 71751
  validation_steps: 50
Continue? (Y/n) Y
Traceback (most recent call last):
  File "/home/richard/anaconda3/envs/clamp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/richard/anaconda3/envs/clamp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/richard/.local/lib/python3.7/site-packages/guild/op_main.py", line 272, in <module>
    main()
  File "/home/richard/.local/lib/python3.7/site-packages/guild/op_main.py", line 53, in main
    _main()
  File "/home/richard/.local/lib/python3.7/site-packages/guild/op_main.py", line 79, in _main
    _apply_plugins()
  File "/home/richard/.local/lib/python3.7/site-packages/guild/op_main.py", line 107, in _apply_plugins
    _apply_plugin(name)
  File "/home/richard/.local/lib/python3.7/site-packages/guild/op_main.py", line 111, in _apply_plugin
    plugin.patch_env()
  File "/home/richard/.local/lib/python3.7/site-packages/guild/plugins/tensorflow_util.py", line 39, in patch_env
    self._try_patch_tensorflow()
  File "/home/richard/.local/lib/python3.7/site-packages/guild/plugins/tensorflow_util.py", line 52, in _try_patch_tensorflow
    tensorflow.summary.FileWriter, "add_summary",
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'
```

Tensorboard is version 1.13.1, tensorboardX is version 1.7

This is not a show stopper for me since I can run with the other command but I thought it might be helpful to report

**Comment by samedii** [comment]
The api has changed in tensorflow 2.0 to `train_writer = tf.summary.create_file_writer('log_dir')`

**Comment by gar1t** [comment]
Ah, indeed - thank you! TF 2.0 is teed up for the next release. I'll update here with status.

**Comment by gar1t** [comment]
@samedii The fix for this will be out this week. In the meantime, you can work around the problem using the pattern used in this example:

https://github.com/guildai/examples/tree/master/tensorflow2

The Guild file (guild.yml) disables all plugins, which is required to skip the logic triggering the exception you reported. The operation also explicitly defines `output-scalars`, which capture the output generated by the Keras training loop.

If your operation generates any additional (or alternative) output, update `output-scalars` in your Guild file accordingly.

If you need any help with regular expressions - just ping us on Slack. We're working on docs with examples for all of this but I wanted to get you an update ASAP.

Thank again for the report!

**Comment by gar1t** [comment]
@samedii Compatibility with TF 2 is now in the latest release `0.6.4`. Please let us know if you're still running into issues!

**Comment by samedii** [comment]
Working nicely!
