### ISSUE TITLE
`windows-curses` does not get installed alongside guildai on Windows

### ISSUE THREAD

**Issue by hkennyv** [guildai/guildai#273]
Hey there, been trying out guild for a bit and love it so far, thank you for the hard work.

I just want to report a minor bug that I think is related to #242 and #244. The solution right now is to do a `pip install windows-curses`, but I think removing this extra step for the user could help.

It seems like `windows-curses` still does not get installed alongside guildai on Windows. I've tested this on both WSL and Mac OS and it does _not_ happen.

**To Reproduce:**

- create new directory & virtualenv
- activate virtualenv
- `pip install guildai`
- `guild check` to ensure guild is being run from the virtualenv
- `guild view` raises the ModuleNotFoundError due to missing ncurses
- `pip list` to check version of guildai (0.7.2)

```
C:\Users\khuynh\me\temp\test>virtualenv venv
created virtual environment CPython3.8.8.final.0-64 in 517ms
  creator CPython3Windows(dest=C:\Users\khuynh\me\temp\test\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\khuynh\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

C:\Users\khuynh\me\temp\test>venv\Scripts\activate

(venv) C:\Users\khuynh\me\temp\test>pip install guildai
Collecting guildai
  Using cached guildai-0.7.2-cp38-cp38-win_amd64.whl (6.6 MB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting requests>=2
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting scikit-optimize>=0.7.1
  Using cached scikit_optimize-0.8.1-py2.py3-none-any.whl (101 kB)
Collecting scikit-learn>=0.19.1
  Using cached scikit_learn-0.24.1-cp38-cp38-win_amd64.whl (6.9 MB)
Collecting filelock>=3.0.12
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Requirement already satisfied: setuptools>=40.6.3 in c:\users\khuynh\me\temp\test\venv\lib\site-packages (from guildai) (52.0.0)
Collecting virtualenv>=15.1.0
  Using cached virtualenv-20.4.2-py2.py3-none-any.whl (7.2 MB)
Collecting click<8,>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting chardet>=3.0.4
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting numpy>=1.16
  Using cached numpy-1.20.1-cp38-cp38-win_amd64.whl (13.7 MB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tabview>=1.4.3
  Using cached tabview-1.4.4-py3-none-any.whl (25 kB)
Collecting daemonize>=2.4.7
  Using cached daemonize-2.5.0-py2.py3-none-any.whl (5.2 kB)
Collecting jinja2>=2.10
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting PyYAML>=2.12
  Using cached PyYAML-5.4.1-cp38-cp38-win_amd64.whl (213 kB)
Collecting Pillow>=5.0
  Using cached Pillow-8.1.1-cp38-cp38-win_amd64.whl (2.2 MB)
Collecting tensorboard>=2.0.0
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
Collecting pkginfo
  Using cached pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting scipy>=0.19.1
  Using cached scipy-1.6.1-cp38-cp38-win_amd64.whl (32.7 MB)
Collecting pyaml>=16.9
  Using cached pyaml-20.4.0-py2.py3-none-any.whl (17 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
Requirement already satisfied: wheel>=0.26 in c:\users\khuynh\me\temp\test\venv\lib\site-packages (from tensorboard>=2.0.0->guildai) (0.36.2)
Collecting absl-py>=0.4
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting grpcio>=1.24.3
  Using cached grpcio-1.36.1-cp38-cp38-win_amd64.whl (3.0 MB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.3-py2.py3-none-any.whl (18 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.27.1-py2.py3-none-any.whl (136 kB)
Collecting protobuf>=3.6.0
  Using cached protobuf-3.15.5-py2.py3-none-any.whl (173 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting appdirs<2,>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: urllib3, pyasn1, idna, chardet, certifi, six, rsa, requests, pyasn1-modules, oauthlib, numpy, cachetools, threadpoolctl, scipy, requests-oauthlib, PyYAML, joblib, google-auth, Werkzeug, tensorboard-plugin-wit, scikit-learn, pyaml, protobuf, MarkupSafe, markdown, grpcio, google-auth-oauthlib, filelock, distlib, appdirs, absl-py, virtualenv, tensorboard, tabview, scikit-optimize, pkginfo, Pillow, jinja2, daemonize, click, guildai
Successfully installed MarkupSafe-1.1.1 Pillow-8.1.1 PyYAML-5.4.1 Werkzeug-1.0.1 absl-py-0.11.0 appdirs-1.4.4 cachetools-4.2.1 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 daemonize-2.5.0 distlib-0.3.1 filelock-3.0.12 google-auth-1.27.1 google-auth-oauthlib-0.4.3 grpcio-1.36.1 guildai-0.7.2 idna-2.10 jinja2-2.11.3 joblib-1.0.1 markdown-3.3.4 numpy-1.20.1 oauthlib-3.1.0 pkginfo-1.7.0 protobuf-3.15.5 pyaml-20.4.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.25.1 requests-oauthlib-1.3.0 rsa-4.7.2 scikit-learn-0.24.1 scikit-optimize-0.8.1 scipy-1.6.1 six-1.15.0 tabview-1.4.4 tensorboard-2.4.1 tensorboard-plugin-wit-1.8.0 threadpoolctl-2.1.0 urllib3-1.26.3 virtualenv-20.4.2

(venv) C:\Users\khuynh\me\temp\test>guild check
guild_version:             0.7.2
guild_install_location:    c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild
guild_home:                C:\Users\khuynh\me\temp\test\venv\.guild
guild_resource_cache:      C:\Users\khuynh\me\temp\test\venv\.guild\cache\resources
installed_plugins:         config_flags, cpu, disk, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
python_exe:                c:\users\khuynh\me\temp\test\venv\scripts\python.exe
platform:                  Windows 10 AMD64
psutil_version:            5.6.3
tensorboard_version:       2.4.1
cuda_version:              not installed
nvidia_smi_version:        not installed
latest_guild_version:      0.7.2

(venv) C:\Users\khuynh\me\temp\test>guild view
Traceback (most recent call last):
  File "c:\users\khuynh\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\khuynh\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\khuynh\me\temp\test\venv\Scripts\guild.exe\__main__.py", line 7, in <module>
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\main_bootstrap.py", line 40, in main
    _main()
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\main_bootstrap.py", line 66, in _main
    guild.main.main()
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\main.py", line 33, in main
    main_cmd.main(standalone_mode=False)
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\click_util.py", line 213, in fn
    return fn0(*(args + (Args(**kw),)))
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\commands\view.py", line 63, in view
    from . import view_impl
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\commands\view_impl.py", line 37, in <module>
    from . import compare_impl
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\commands\compare_impl.py", line 35, in <module>
    from guild import tabview
  File "c:\users\khuynh\me\temp\test\venv\lib\site-packages\guild\tabview.py", line 18, in <module>
    import curses
  File "c:\users\khuynh\appdata\local\programs\python\python38\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

(venv) C:\Users\khuynh\me\temp\test>pip list
Package                Version
---------------------- ---------
absl-py                0.11.0
appdirs                1.4.4
cachetools             4.2.1
certifi                2020.12.5
chardet                4.0.0
click                  7.1.2
daemonize              2.5.0
distlib                0.3.1
filelock               3.0.12
google-auth            1.27.1
google-auth-oauthlib   0.4.3
grpcio                 1.36.1
guildai                0.7.2
idna                   2.10
Jinja2                 2.11.3
joblib                 1.0.1
Markdown               3.3.4
MarkupSafe             1.1.1
numpy                  1.20.1
oauthlib               3.1.0
Pillow                 8.1.1
pip                    21.0.1
pkginfo                1.7.0
protobuf               3.15.5
pyaml                  20.4.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
PyYAML                 5.4.1
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7.2
scikit-learn           0.24.1
scikit-optimize        0.8.1
scipy                  1.6.1
setuptools             52.0.0
six                    1.15.0
tabview                1.4.4
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
threadpoolctl          2.1.0
urllib3                1.26.3
virtualenv             20.4.2
Werkzeug               1.0.1
wheel                  0.36.2

(venv) C:\Users\khuynh\me\temp\test>
```

**Comment by gar1t** [comment]
Thank you for the excellent detailed report! I'm able to recreate this. Please look for a fix in the next release.

**Comment by gar1t** [comment]
It looks like this was fixed in the packaging rework that @tekumara prompted in #249. You can verify that this work by installing the pre-release version of Guild using `pip install --upgrade --pre guildai`.

**Comment by gar1t** [comment]
I'm going to close this for now. If there's a recurring issue with 0.7.3 we can reopen. Thanks again!

**Comment by hkennyv** [comment]
Thanks! I haven't had a chance to come back to this yet, I'll update if I do.
