### ISSUE TITLE
`loguniform` error isn't correctly reported for optimizers other than random

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#291]
Using optimizers other than the random one, the `loguniform` distribution with wrong arguments aren't correctly reported:

```bash
root@d96c1f1f7ab5:/workspace# guild run -y run_vpg --optimizer gbrt entropy=loguniform[1e-2:1e-6]
ERROR: [guild] flags for batch (batch_size=1000, decay=3.0e-05, dim_repr=1, entropy=loguniform[1e-2:1e-6], lr=0.0001, num_steps=50000, obs_ratio=100, platform=gpu, seed=0, time_delta=10.0, use_jit=yes, use_log=yes) do not contain any search dimensions
Try specifying a range for one or more flags as NAME=[MIN:MAX].
```

However, using the random optimizer, it correctly reports that the values of the arguments are problematic:
```bash
root@d96c1f1f7ab5:/workspace# guild run -y run_vpg --optimizer + entropy=loguniform[1e-2:1e-6]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_main.py", line 41, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_main.py", line 25, in main
    trials = _batch_trials(batch_run)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_main.py", line 32, in _batch_trials
    all_trials = batch_util.expanded_batch_trials(batch_run, random_seed)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 386, in expanded_batch_trials
    return expand_flags(flag_vals, random_seed)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 301, in expand_flags
    expanded = _expand_flags_base(flag_vals)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 308, in _expand_flags_base
    flags_list = [_expand_flag(name, val) for name, val in sorted(flag_vals.items())]
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 308, in <listcomp>
    flags_list = [_expand_flag(name, val) for name, val in sorted(flag_vals.items())]
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 315, in _expand_flag
    return [(name, _flag_function_or_val(x, name)) for x in val]
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 315, in <listcomp>
    return [(name, _flag_function_or_val(x, name)) for x in val]
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 326, in _flag_function_or_val
    return _FlagFunction(name, args, flag_name, val)
  File "/usr/local/lib/python3.8/dist-packages/guild/batch_util.py", line 333, in __init__
    self.dim, self.initial = skopt_util.function_dim(name, args, "dummy")
  File "/usr/local/lib/python3.8/dist-packages/guild/plugins/skopt_util.py", line 162, in function_dim
    return _real_dim(args, "log-uniform", func_name, flag_name)
  File "/usr/local/lib/python3.8/dist-packages/guild/plugins/skopt_util.py", line 181, in _real_dim
    return space.Real(*real_init_args), initial
  File "/usr/local/lib/python3.8/dist-packages/skopt/space/space.py", line 255, in __init__
    raise ValueError("the lower bound {} has to be less than the"
ValueError: the lower bound 0.01 has to be less than the upper bound 1e-06
```

**Comment by gar1t** [comment]
Thank you for the report! I'm able to recreate this. Refer to [this resolution doc](https://github.com/guildai/issue-resolution/tree/master/291-loguniform-error-isn-t-correctly-reported-for-optimizers-other-than-random) for additional details.
