### ISSUE TITLE
ValueError at the commented-out last line in Jupyter notebook

### ISSUE THREAD

**Issue by sudodo** [guildai/guildai#301]
## Issue
ValueError  occurs by `guild run A.ipynb`
```
jovyan@2abdf81bf421:~/work/user/test$ guild run A.ipynb
You are about to run Untitled.ipynb
  n_epoch: 0
Continue? (Y/n) Y
INFO: [guild] Initializing Untitled.ipynb for run
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/tokenize.py", line 278, in untokenize
    out = ut.untokenize(iterable)
  File "/opt/conda/lib/python3.9/tokenize.py", line 212, in untokenize
    self.add_whitespace(start)
  File "/opt/conda/lib/python3.9/tokenize.py", line 173, in add_whitespace
    raise ValueError("start ({},{}) precedes previous end ({},{})"
ValueError: start (2,3) precedes previous end (3,0)
```

A.ipynb has exactly one cell as the follows:
```
n_epoch = 0
# this comment line causes the error!
```

The error resolves when removing the final line
```
# Any comment except the final line does not raise the error.
n_epoch = 0
```

In my environment, every time I add a comment in the last line of a cell of an ipynb file, I encounter the error.

### Guild AI
Version: 0.7.3
### Python
Python 3.9.2
### Jupyter versions
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.24.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
### OS
Ubuntu 16.04.7 LTS

Jupyter is running on a docker.

**Comment by copaah** [comment]
Encountering same error.

**Comment by johandicap** [comment]
Hi. This might be related to these findings: https://github.com/vyperlang/vyper/issues/1161#issuecomment-451097515

**Comment by gar1t** [comment]
This is fixed in master and will be available in 0.7.5. Thanks for the terrific report!
