### ISSUE TITLE
guild search does not work in pyenv (circular import)

### ISSUE THREAD

**Issue by kpe** [guildai/guildai#313]
(I have only recently found guildai - and must say it is really awesome - in a multitude of ways actually)

I have the problem however that `guild search` does not work in my `pyenv`, and just want to check if this is a guild problem, or related to my environment.

Steps to reproduce:
```bash
mkdir /tmp/t
cd /tmp/t
pyenv install 3.9.8
pyenv local 3.9.8
pyenv exec python -m venv .venv
source .venv/bin/activate
pip install -U pip guildai

guild search mnist
```
will result to
```python
Traceback (most recent call last):
  File "/tmp/g/.venv/bin/guild", line 8, in <module>
    sys.exit(main())
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/main_bootstrap.py", line 40, in main
    _main()
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/main_bootstrap.py", line 66, in _main
    guild.main.main()
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/main.py", line 33, in main
    main_cmd.main(standalone_mode=False)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/g/.venv/lib64/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/click_util.py", line 213, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/commands/search.py", line 38, in search
    search_impl.main(args)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/commands/search_impl.py", line 24, in main
    formatted = [_format_package(pkg) for pkg in _search(args)]
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/commands/search_impl.py", line 30, in _search
    return pip_util.search(spec, operator)
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/pip_util.py", line 178, in search
    _ensure_search_logger()
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/pip_util.py", line 193, in _ensure_search_logger
    from pip._vendor.requests.packages.urllib3 import connectionpool
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/external/pip/_vendor/requests/__init__.py", line 94, in <module>
    from pip._internal.compat import WINDOWS
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/external/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/external/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/external/pip/_internal/index.py", line 24, in <module>
    from pip._internal.download import HAS_TLS, is_url, path_to_url, url_to_path
  File "/tmp/g/.venv/lib64/python3.9/site-packages/guild/external/pip/_internal/download.py", line 325, in <module>
    class PipSession(requests.Session):
AttributeError: partially initialized module 'pip._vendor.requests' has no attribute 'Session' (most likely due to a circular import)

```

**Comment by gar1t** [comment]
Thanks for the report! This is technically fixed in master and will be available in the next release, however PyPI's XML-RPC interface is disabled at this time so the search function doesn't work. This is true of even `pip search`.
