### ISSUE TITLE
Guild compare failing on imported runs (FileNotFoundError)

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#35]
After recently transferring my guild runs to a different machine using the export/import functionality, the guild compare operation is now failing, with the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/Documents/PhD/symbolic-goal-generation/guild.yml`
(Which is the path to my guild file on the old machine).
```
Traceback (most recent call last):
  File "/home/achester/anaconda3/envs/goal-gen/bin/guild", line 10, in <module>
    sys.exit(main())
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/main_bootstrap.py", line 48, in main
    guild.main.main()
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/main.py", line 32, in main
    _main()
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/main.py", line 38, in _main
    main_cmd.main(standalone_mode=False)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/external/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/external/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/external/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/external/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/external/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/click_util.py", line 146, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare.py", line 177, in compare
    compare_impl.main(args)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 54, in main
    _tabview(args)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 121, in _tabview
    _tabview_actions())
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/tabview.py", line 209, in view_runs
    info="Guild run comparison",
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/tabview/tabview.py", line 1385, in view
    info=info)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/tabview/tabview.py", line 1305, in main
    Viewer(stdscr, *args, **kwargs).run()
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/tabview.py", line 77, in __init__
    data, logs = self._init_data()
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/tabview.py", line 85, in _init_data
    data, logs = self.get_data()
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 130, in f
    cols_table = _cols_table(runs, args, index)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 171, in _cols_table
    for run in runs]
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 171, in <listcomp>
    for run in runs]
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 176, in _run_cols
    _op_cols(run, args, parse_cache, index),
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 204, in _op_cols
    compare = _run_op_compare(run, index)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 222, in _run_op_compare
    _default_run_compare], run, index)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/util.py", line 49, in find_apply
    result = f(*args)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/commands/compare_impl.py", line 227, in _try_guildfile_compare
    gf = guildfile.from_run(run)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/guildfile.py", line 1363, in from_run
    return from_file(gf_path)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/guildfile.py", line 1317, in from_file
    gf = _load_guildfile(src, extends_seen)
  File "/home/achester/anaconda3/envs/goal-gen/lib/python3.7/site-packages/guild/guildfile.py", line 1327, in _load_guildfile
    data = yaml.safe_load(open(src, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/Documents/PhD/symbolic-goal-generation/guild.yml'
```

**Comment by gar1t** [comment]
I was able to recreate this with 0.6.5. I created an issue project to help recreate the behavior:

https://github.com/guildai/issues/tree/master/35-compare-failing-on-imported-runs

A fix for this has been committed and will land in 0.6.6.

**Comment by AndrewPaulChester** [comment]
I've tested and confirmed this works on 0.6.6rc1
