### ISSUE TITLE
pandas requires installation from source on python 3.10

### ISSUE THREAD

**Issue by msarahan** [guildai/guildai#351]
This makes the python 3.10 CI job take about 15 minutes longer than it should. We may want to switch to a conda-based stack where possible to obtain these dependencies more quickly.

**Comment by msarahan** [comment]
It's because we have pandas pinned in guild/tests/requirements.txt to `<1.2`, and there are no wheels for newer python with the older version. We should try to remove that pin and fix whatever the new pandas might break.

**Comment by msarahan** [comment]
I unpinned pandas and hit this error: 

```
Exception raised:
    Traceback (most recent call last):
      File "/home/msarahan/mambaforge/envs/guildai/lib/python3.10/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest None[0]>", line 2, in <module>
      File "/home/msarahan/mambaforge/envs/guildai/lib/python3.10/site-packages/pandas/core/frame.py", line 3488, in __getitem__
        return self._slice(indexer, axis=0)
      File "/home/msarahan/mambaforge/envs/guildai/lib/python3.10/site-packages/pandas/core/generic.py", line 3929, in _slice
        result = result.__finalize__(self)
      File "/home/msarahan/mambaforge/envs/guildai/lib/python3.10/site-packages/pandas/core/generic.py", line 5549, in __finalize__
        self.flags.allows_duplicate_labels = other.flags.allows_duplicate_labels
    AttributeError: 'function' object has no attribute 'allows_duplicate_labels'
```

Seems like it will take some time to investigate and fix.
