### ISSUE TITLE
Deleting batch runs gives `TypeError: sequence item 0: expected str instance, Process found`

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#377]
This sometimes happens when I want to delete a batched runs. e.g.:

```
_
You are about to delete the following runs:
  [b9923bea]  catch:train   2022-04-17 06:51:23  running  big_batch_size=500 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [9cbac747]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=8000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [4959f94c]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=6000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [849e0e8a]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=4000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [a0670d49]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=3000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [23a0dd4d]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=2000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [ae7eb758]  catch:train   2022-04-17 06:51:23  pending  big_batch_size=1000 game_num_cols=6 game_num_rows=6 num_epochs=500 repr_channels=6
  [d0befcfd]  catch:train+  2022-04-17 06:51:21  running  
Delete 8 run(s)? (Y/n) y
WARNING: One or more runs are still running and will be stopped before being deleted.
Really delete these runs? (y/N) y
Stopping b9923bea863e471f9686a425a821258d (pid 26263)
Stopping d0befcfdcf6d49aa99a408dbf43307db (pid 26229)
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/bin/guild", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/main_bootstrap.py", line 40, in main
    _main()
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/main_bootstrap.py", line 66, in _main
    guild.main.main()
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/main.py", line 33, in main
    main_cmd.main(standalone_mode=False)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/click_util.py", line 213, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_delete.py", line 84, in delete_runs
    runs_impl.delete_runs(args, ctx)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 693, in delete_runs
    _delete_runs(args, ctx)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 729, in _delete_runs
    runs_op(
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 671, in runs_op
    op_callback(selected)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 722, in delete
    _stop_run(run, no_wait=True)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 1215, in _stop_run
    _try_stop_local_run(run)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 1242, in _try_stop_local_run
    _handle_non_stopped_pids(alive)
  File "/root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild/commands/runs_impl.py", line 1246, in _handle_non_stopped_pids
    alive_desc = ", ".join(alive)
TypeError: sequence item 0: expected str instance, Process found
```

Location:
https://github.com/guildai/guildai/blob/889498542dcbd6a101ee6846d61353d691b3f2e7/guild/commands/runs_impl.py#L1246

I think this might have to do with psutil version, so here's my version:
```
root@e9e378064bec:/moozi# pip freeze | grep psutil
psutil==5.9.0
```

Also `guild check`:
```
root@e9e378064bec:/moozi# guild check
guild_version:             0.8.0
guild_install_location:    /root/.local/share/virtualenvs/moozi-g1CZ00E9/lib/python3.8/site-packages/guild
guild_home:                /root/.local/share/virtualenvs/moozi-g1CZ00E9/.guild
guild_resource_cache:      /root/.local/share/virtualenvs/moozi-g1CZ00E9/.guild/cache/resources
installed_plugins:         config_flags, cpu, dask, disk, dvc, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.8.12 (default, Apr 14 2022, 23:11:54) [GCC 7.5.0]
python_exe:                /root/.local/share/virtualenvs/moozi-g1CZ00E9/bin/python
platform:                  Linux 4.15.0-118-generic x86_64
psutil_version:            5.9.0
tensorboard_version:       2.8.0
cuda_version:              11.4.152
nvidia_smi_version:        450.51.06
latest_guild_version:      0.8.0
```

**Comment by gar1t** [comment]
Ah, very helpful - thank you for the report! Looks like their API changed - we'll get this fixed ASAP.

**Comment by davzaman** [comment]
+1 To this problem but with queues!
