### ISSUE TITLE
Issue with missing content in nbexec with Python 3.10

### ISSUE THREAD

**Issue by msarahan** [guildai/guildai#389]
Couple of examples below. More at https://github.com/guildai/guildai/runs/6164266467?check_suite_focus=true

```
+File "/home/runner/work/guildai/guildai/test-env/lib/python3.10/site-packages/guild/tests/notebook-exec.md", line 120, in notebook-exec.md
    +Failed example:
    +    nb_output(path(run.dir, "flags.ipynb"))
    +Expected:
    +    z: 3.123
    +    c: 2.200000
    +    Hello hello!
    +    A second line for hello.
    +    A third line for hello.
    +Got:
    +    z: 3
    +    c: 1.200000
    +    hello
    +**********************************************************************
    +1 items had failures:
    +   7 of  38 in notebook-exec.md
    +***Test Failed*** 7 failures.
    +  notebooks: **********************************************************************
    +File "/home/runner/work/guildai/guildai/test-env/lib/python3.10/site-packages/guild/tests/notebooks.md", line 120, in notebooks.md
    +Failed example:
    +    apply_flags("x = -1\ny = 2", x=666, y=777)
    +Exception raised:
    +    Traceback (most recent call last):
    +      File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/doctest.py", line 1346, in __run
    +        exec(compile(example.source, filename, "single",
    +      File "<doctest notebooks.md[22]>", line 1, in <module>
    +        apply_flags("x = -1\ny = 2", x=666, y=777)
    +      File "<doctest notebooks.md[10]>", line 3, in apply_flags
    +        out = _replace_flag_assign_vals(src, state)
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.10/site-packages/guild/plugins/nbexec.py", line 266, in _replace_flag_assign_vals
    +        return _maybe_strip_nl(nl_added, repl_source)
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.10/site-packages/guild/plugins/nbexec.py", line 271, in _maybe_strip_nl
    +        assert source[-1:] == "\n", source
    +    AssertionError: x = 666
    +    y = 777
    +**********************************************************************
```

These tests all pass with python 3.6-3.9. I haven't been able to isolate the behavior change that is causing issues yet.

**Comment by msarahan** [comment]
Tracked this to a difference in the evaluation of whether a string is a python expression or not. The code in question (from https://github.com/guildai/guildai/blob/main/guild/plugins/nbexec.py#L446-L454)

```
def _is_python_expr(tokens):
    s = tokenize.untokenize(tokens).strip()
    try:
        m = ast.parse(s)
    except SyntaxError:
        return False
    else:
        assert len(m.body) == 1 and isinstance(m.body[0], ast.Expr), m.body
        return True
```

In the debugger, I found that the offending behavior happens when processing the second line from the flags.ipynb file:

```
x = 1
y : int = 2
z = x + y
print("z: %s" % z)
```

Since that fails, it seems like any further output of the string being processed just stops.

If I run the ast.parse(s) manually, we see that it is a new behavior with Python 3.10's handling of indentation:
```
Traceback (most recent call last):
  File "/home/msarahan/code/guildai/guild/plugins/nbexec.py", line 449, in _is_python_expr
    m = ast.parse(s)
  File "/home/msarahan/mambaforge/envs/guildai_310/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    2
IndentationError: unexpected indent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/msarahan/mambaforge/envs/guildai_310/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    2
IndentationError: unexpected indent
```
This exception does not occur with earlier python versions. The string that is going in to the `ast.parse(s)` is `'\\\n          2'`

**Comment by msarahan** [comment]
This might have been related to https://bugs.python.org/issue46091.

**Comment by msarahan** [comment]
fixed in https://github.com/guildai/guildai/commit/c5b06bf900250c869f15d92d788d3c7a8262b89d#diff-3558ae74654d25d04e6dd09717fca35a387a515b363dcb18d024098144cc78ca
