### ISSUE TITLE
python 3.6(.4) issue:  AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#4]
```
$ guild check
guild_version:             0.3.0.dev19
guild_home:                /Users/cfregly/.guild
guild_install_location:    /Users/cfregly/miniconda3/lib/python3.6/site-packages/guild
installed_plugins:         cloudml, cpu, disk, gpu, keras, memory
python_version:            3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
tensorflow_version:        1.6.0
tensorflow_cuda_support:   no
tensorflow_gpu_available:  no
tensorboard_version:       1.6.0
libcuda_version:           not loaded
libcudnn_version:          not loaded
nvidia_smi_version:        not installed
```
```
$ guild train softmax
You are about to run mnist/mnist-softmax:train
  batch-size: 100
  epochs: 10
Continue? (Y/n)
Resolving mnist/dataset dependency
Starting new HTTP connection (1): yann.lecun.com
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz (9.9MB)
  100% |████████████████████████████████| 9.9MB 16.2MB/s
Starting new HTTP connection (1): yann.lecun.com
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Starting new HTTP connection (1): yann.lecun.com
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz (1.6MB)
  100% |████████████████████████████████| 1.7MB 10.6MB/s
Starting new HTTP connection (1): yann.lecun.com
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Failed to import the site module
Traceback (most recent call last):
  File "/Users/cfregly/miniconda3/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Users/cfregly/miniconda3/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/cfregly/miniconda3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/cfregly/miniconda3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/cfregly/miniconda3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/cfregly/miniconda3/lib/python3.6/sysconfig.py", line 607, in get_config_var
    return get_config_vars().get(name)
  File "/Users/cfregly/miniconda3/lib/python3.6/sysconfig.py", line 586, in get_config_vars
    import _osx_support
  File "/Users/cfregly/miniconda3/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/Users/cfregly/miniconda3/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by cfregly** [comment]
mac osx 10.13

**Comment by cfregly** [comment]
Workaround Solution:  Uninstall enum34
```
pip uninstall enum34
```

See here for more details:  https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by gar1t** [comment]
I'm going o (re) close this for now and if it comes up again we can look  to add something to check (and the site).
