### ISSUE TITLE
Weird interaction between ray and guildai

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#408]
I've been encountering this problem that a script that runs perfectly fine with `python script.py` cannot be ran with `guild run script.py`. I'm not sure it's ray's problem or guildai's problem, but my guess is that guildai's launching process doesn't reproduce the same context as `python script.py`.

Here's a minimum script to reproduce the problem:
```python
import ray
from ray import tune


def get_score(config):
    print(config)
    return config["x"] ** 2


def run_trial(config):
    score = get_score(config)
    tune.report(score=score)


if __name__ == "__main__":
    ray.init(num_cpus=72)
    analysis = tune.run(
        run_trial,
        num_samples=2,
        metric="score",
        mode="max",
        config={"x": tune.uniform(0, 1)},
        resources_per_trial=tune.PlacementGroupFactory([{}, {"CPU": 2}]),
    )
    print(f"{analysis.best_trial.config=}")
```

Error message when I run
```
WARNING: Skipping potential source code file ./logs/log.txt because it's too big. To control which files are copied, define 'sourcecode' for the operation in a Guild file.
2022-05-09 15:21:41,958 WARNING function_runner.py:598 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2022-05-09 15:21:41,988 WARNING tune.py:636 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.
2022-05-09 15:21:42,171 INFO trial_runner.py:803 -- starting run_trial_41bbc_00000
Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 719, in _wait_and_handle_event
    self._on_pg_ready(next_trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 804, in _on_pg_ready
    if not _start_trial(next_trial) and next_trial.status != Trial.ERROR:
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 796, in _start_trial
    self._callbacks.on_trial_start(
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/callback.py", line 256, in on_trial_start
    callback.on_trial_start(**info)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 533, in on_trial_start
    self._get_trial_syncer(trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 466, in _get_trial_syncer
    self._syncers[trial] = self._create_trial_syncer(trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 470, in _create_trial_syncer
    return get_node_syncer(
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 448, in get_node_syncer
    sync = log_sync_template()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 118, in log_sync_template
    if not distutils.spawn.find_executable("rsync"):
AttributeError: module 'distutils' has no attribute 'spawn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 454, in <module>
    main()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 67, in main
    _main()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 97, in _main
    _try_module(arg1, rest_args)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 155, in _try_module
    _dispatch_module_exec(_flags_interface(args), module_info)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 308, in _dispatch_module_exec
    _exec_module(module_info, args, flags)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 345, in _exec_module
    _gen_exec(exec_script, module_info)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 359, in _gen_exec
    exec_cb()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/op_main.py", line 343, in exec_script
    python_util.exec_script(module_info.mod_path, globals, mod_name=mod_name)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild/python_util.py", line 459, in exec_script
    exec(code, script_globals)
  File "/home/zeyi/miniconda3/envs/compiler_gym/.guild/runs/d68ca333ac244e6b9c361ccac80cfaca/.guild/sourcecode/sandbox.py", line 20, in <module>
    analysis = tune.run(
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/tune.py", line 672, in run
    runner.step()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 767, in step
    self._wait_and_handle_event(next_trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 747, in _wait_and_handle_event
    raise TuneError(traceback.format_exc())
ray.tune.error.TuneError: Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 719, in _wait_and_handle_event
    self._on_pg_ready(next_trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 804, in _on_pg_ready
    if not _start_trial(next_trial) and next_trial.status != Trial.ERROR:
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 796, in _start_trial
    self._callbacks.on_trial_start(
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/callback.py", line 256, in on_trial_start
    callback.on_trial_start(**info)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 533, in on_trial_start
    self._get_trial_syncer(trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 466, in _get_trial_syncer
    self._syncers[trial] = self._create_trial_syncer(trial)
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 470, in _create_trial_syncer
    return get_node_syncer(
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 448, in get_node_syncer
    sync = log_sync_template()
  File "/home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/ray/tune/syncer.py", line 118, in log_sync_template
    if not distutils.spawn.find_executable("rsync"):
AttributeError: module 'distutils' has no attribute 'spawn'
```

The above script runs without error if I use `python script.py` instead of `guild run script.py`

`guild check`:

```
❯ guild check
guild_version:             0.8.0
guild_install_location:    /home/zeyi/miniconda3/envs/compiler_gym/lib/python3.8/site-packages/guild
guild_home:                /home/zeyi/miniconda3/envs/compiler_gym/.guild
guild_resource_cache:      /home/zeyi/miniconda3/envs/compiler_gym/.guild/cache/resources
installed_plugins:         config_flags, cpu, dask, disk, dvc, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) [GCC 9.4.0]
python_exe:                /home/zeyi/miniconda3/envs/compiler_gym/bin/python3.8
platform:                  Linux 5.4.0-97-generic x86_64
psutil_version:            5.9.0
tensorboard_version:       2.8.0
cuda_version:              11.2
nvidia_smi_version:        460.32.03
latest_guild_version:      unknown (error)
```

Ray version:
```
❯ pip freeze | grep ray
ray==1.12.0
```

Related issues: https://github.com/influxdata/influxdb-python/issues/798

**Comment by msarahan** [comment]
I think it's likely the monkeypatching that setuptools is doing lately. Guild is probably importing setuptools, which causes the monkeypatching of distutils to happen, which then undermines ray.

Try setting an env var:

`export SETUPTOOLS_USE_DISTUTILS=stdlib`

If this makes the problem go away, it is definitely the setuptools monkeypatching. Short term answer is that you need to set that environment variable. Long term answer is that we need to avoid importing setuptools unless absolutely necessary.

**Comment by uduse** [comment]
@msarahan Thank you for your fast response. This does solve the problem. 🎉 Is there any notable side-effects of using such environment variable in guild?

**Comment by msarahan** [comment]
I don't think so, but it's something to keep in mind. It would especially effect guild's package system if it affected anything. If you don't use that part, it's probably safe.

You may want to raise an issue or PR on Ray's repo, because distutils is deprecated: https://peps.python.org/pep-0632/
