### ISSUE TITLE
ERROR: [guild.perf] reading summary values

### ISSUE THREAD

**Issue by dschwertfeger** [guildai/guildai#420]
I'm getting an `ERROR: [guild.perf] reading summary values` when trying out Guild on a small test project.

The problem seems to be here:

https://github.com/guildai/guildai/blob/0c8a671ca324ba025fc9e695a6834b2fdba23d7d/guild/plugins/perf.py#L37

Looks like `steps` is an `EagerTensor`, whereas `seconds` is a `float`.

Here's the full trace:

```
Epoch 1/100
175/175 [==============================] - 15s 82ms/step - loss: 6.3266 - categorical_accuracy: 0.5089 - val_loss: 1.3913 - val_categorical_accuracy: 0.5349
Epoch 2/100
175/175 [==============================] - ETA: 0s - loss: 4.6419 - categorical_accuracy: 0.6308ERROR: [guild.perf] reading summary values
Traceback (most recent call last):
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/guild/plugins/summary_util.py", line 188, in _summary_values
    vals = self.read_summary_values(global_step)
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/guild/plugins/perf.py", line 37, in read_summary_values
    stats["performance/sec_per_step"] = seconds / steps
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
TypeError: Cannot convert 16.479862213134766 to EagerTensor of dtype int64
175/175 [==============================] - 16s 93ms/step - loss: 4.6419 - categorical_accuracy: 0.6308 - val_loss: 1.0224 - val_categorical_accuracy: 0.6773
Epoch 3/100
175/175 [==============================] - ETA: 0s - loss: 4.0071 - categorical_accuracy: 0.6777ERROR: [guild.perf] reading summary values
Traceback (most recent call last):
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/guild/plugins/summary_util.py", line 188, in _summary_values
    vals = self.read_summary_values(global_step)
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/guild/plugins/perf.py", line 37, in read_summary_values
    stats["performance/sec_per_step"] = seconds / steps
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/dsc/.pyenv/versions/3.8.7/envs/wendy/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
TypeError: Cannot convert 33.17161202430725 to EagerTensor of dtype int64
```

How do you suggest resolving this?

**Comment by dschwertfeger** [comment]
Update.

I'm running the exact same script from a Guild File (`guild.yml`) instead of running the script directly and I'm not getting this error. 🤔

**Comment by msarahan** [comment]
I don't understand the behavior you're seeing. It seems like there's just a type error there, and the steps need to be changed explicitly to a float dtype before that division. It would be nice if tensorflow handled this casting, but it's probably better to error and avoid any unpredictable issues with loss of precision in arbitrary contexts.

Thanks for reporting. Should be a simple fix.
