### ISSUE TITLE
Protocol buffers for tests need to be regenerated

### ISSUE THREAD

**Issue by msarahan** [guildai/guildai#421]
We have lots of tests failing, looks like this is biting us: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```
+File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/guild/tests/tfevents.md", line 147, in tfevents.md
    +Failed example:
    +    subdir_writer.add_scalar("e", 8.0)
    +Exception raised:
    +    Traceback (most recent call last):
    +      File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/doctest.py", line 1337, in __run
    +        compileflags, 1), test.globs)
    +      File "<doctest tfevents.md[36]>", line 1, in <module>
    +        subdir_writer.add_scalar("e", 8.0)
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/guild/summary.py", line 108, in add_scalar
    +        self._add_summary(_ScalarSummary(tag, val), step)
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/guild/summary.py", line 147, in _ScalarSummary
    +        return tensorboard.Summary(tag, simple_value=val)
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/guild/plugins/tensorboard.py", line 38, in Summary
    +        from tensorboard.compat.proto.summary_pb2 import Summary
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    +        from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    +        from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    +        from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 42, in <module>
    +        serialized_options=None, file=DESCRIPTOR),
    +      File "/home/runner/work/guildai/guildai/test-env/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    +        _message.Message._CheckCalledFromGeneratedFile()
    +    TypeError: Descriptors cannot not be created directly.
    +    If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
    +    If you cannot immediately regenerate your protos, some other possible workarounds are:
    +     1. Downgrade the protobuf package to 3.20.x or lower.
    +     2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
    +<BLANKLINE>
    +    More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by gar1t** [comment]
We don't generate protobuf shims. This may be related to a pegging of an upstream library version. We use tensorboard natively to write TF event logs. We've confirmed that this is not a regression in tensorboard - or maybe an API has changed and we're triggering some stale code?

**Comment by gar1t** [comment]
https://github.com/protocolbuffers/protobuf/issues/10051

**Comment by gar1t** [comment]
This appears to be a massive Google-wide breakage. Downstream libs are resorting to pegging their req to `protobuf==3.20.1` which I think is our only option for this for now.

**Comment by msarahan** [comment]
protobuf pinned to <4 in https://github.com/guildai/guildai/commit/17ca691a58d41ba0502775dc97ec7ad2c1f3a0ec; closing
