### ISSUE TITLE
Crash when trying to use wandb for remote logging

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#434]
I'm running multiple machines and figured it would be nice to have some way to try and centralize live logging. Wanted to try out wandb for this since it looked very easy and like it would work with guild.

Was hoping this was all it would take:
```
    wandb.init(
        project="my-project",
        name=Path(".guild/attrs/label").read_text()
        id=config["run_id"],
        sync_tensorboard=True,
    )
```

But then I'm getting this error:
```
➜ guild run train -y
Refreshing flags...                                                                                                                                                                                        
Resolving splits dependency                   
Resolving config dependency
wandb: Currently logged in as: samedii. Use `wandb login --relogin` to force relogin
Problem at: /home/richard/Documents/trafikverket-wire-damage-generation/.venv/.guild/runs/65ce589556a04fccbd8fe997ea9c04db/.guild/sourcecode/operations/train.py 30 train
Traceback (most recent call last):
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 523, in init
    backend.ensure_launched()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 215, in ensure_launched
    self._module_main_install()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 116, in _module_main_install
    main_module.__spec__ = main_mod_spec
AttributeError: 'dict' object has no attribute '__spec__'
```

Not finding any information on this. Code works fine without guild. Any ideas what might be the culprit and do you think it would be an easy fix?

**Comment by samedii** [comment]
Seems more like a wandb issue. Posted here https://github.com/wandb/client/issues/3859 and was able to hack the source code to get around it
