### ISSUE TITLE
TypeError when stopping a run

### ISSUE THREAD

**Issue by Zatteliet** [guildai/guildai#483]
I accidentally interrupted a run, giving it the "running" status. Stopping (and by extension deleting) it raises a TypeError.

Command and output:

```
(.venv) ➜  python git:(master) ✗ guild -H ~/.guild runs stop
You are about to stop the following runs:
  [9cd71ff9]  datamaker:make_fx  2023-02-27 14:27:58  running  steps.augment_bodyparts.char_label=CHAR steps.augment_bodyparts.enabled=no steps.merge_labels.enabled=yes steps.m
Stop 1 run(s)? (y/N) y
Stopping 9cd71ff9fab748ca8c9d06d17f412018 (pid 16556)
Traceback (most recent call last):
  File "/home/camiel/.pyenv/versions/3.10.7/bin/guild", line 8, in <module>
    sys.exit(main())
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/main_bootstrap.py", line 29, in main
    _main()
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/main_bootstrap.py", line 54, in _main
    guild.main.main()
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/main.py", line 30, in main
    main_cmd.main(standalone_mode=False)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/click_util.py", line 239, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_stop.py", line 76, in stop_runs
    runs_impl.stop_runs(args, ctx)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1218, in stop_runs
    _stop_runs(args, ctx)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1236, in _stop_runs
    runs_op(
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 666, in runs_op
    _apply_runs_op_callback(op_callback, selected, formatted)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 676, in _apply_runs_op_callback
    op_callback(selected)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1230, in stop_f
    _stop_run(run, args.no_wait)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1254, in _stop_run
    _try_stop_local_run(run)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1281, in _try_stop_local_run
    _handle_non_stopped_pids(alive)
  File "/home/camiel/.pyenv/versions/3.10.7/lib/python3.10/site-packages/guild/commands/runs_impl.py", line 1285, in _handle_non_stopped_pids
    alive_desc = ", ".join(alive)
TypeError: sequence item 0: expected str instance, Process found
```

**Comment by gar1t** [comment]
Thank you for the report! We'll get this cleaned up for the next release.

Guild was trying to print an error message there for processes it could not stop. You might confirm that the underlying run processes are terminated (this condition sometimes reflects zombie processes that won't be cleared until the system is restarted... they're otherwise harmless)
