### ISSUE TITLE
Logging a scalar fails with Tensorboard Import Error

### ISSUE THREAD

**Issue by pspeter** [guildai/guildai#53]
When I print out a scalar `print("test: 1.0")` and run the script using guild run, the scalar will not be logged. Instead, I get an error message and a stack trace while the script is running (it will continue to the end though):

```
test: 1.0
ERROR: error in output callback (will be removed)
Traceback (most recent call last):
  File "/.../lib/python3.6/site-packages/guild/op_util.py", line 191, in _gen_tee_run
    self._output_cb.write(line_bytes)
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 245, in write
    self._writer.add_scalar(key, val, self._step)
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 101, in add_scalar
    self._add_summary(_ScalarSummary(tag, val), step)
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 98, in _add_summary
    self._get_writer().add_event(event)
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 90, in _get_writer
    self._writer = self._writer_init()
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 85, in <lambda>
    filename_suffix=filename_suffix)
  File "/.../lib/python3.6/site-packages/guild/summary.py", line 51, in __init__
    from tensorboard.summary.writer import event_file_writer as wr
```

I'm using Tensorboard Version 13.1, looks like the tensorboard.summary.writer module is only available in 14.0.

**Comment by gar1t** [comment]
Thank you! I'll get this fixed for the next release.

**Comment by gar1t** [comment]
Closing as Guild now explicitly requires TensorBoard 1.15 or higher.
