### ISSUE TITLE
guild compare raises image not found

### ISSUE THREAD

**Issue by BrentDorsey** [guildai/guildai#7]
`
$ guild compare
Traceback (most recent call last):
  File "/Users/bdorsey/anaconda3/bin/guild", line 11, in <module>
    sys.exit(main())
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/main_bootstrap.py", line 44, in main
    guild.main.main()
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/main.py", line 30, in main
    _main()
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/main.py", line 36, in _main
    guild.commands.main.main(standalone_mode=False)
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 731, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 706, in main
    rv = self.invoke(ctx)
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 1080, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 907, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 544, in invoke
    return callback(*args, **kwargs)
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/click_util.py", line 140, in fn
    return fn0(*(args + (Args(kw),)))
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/commands/compare.py", line 69, in compare
    from . import compare_impl
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/commands/compare_impl.py", line 26, in <module>
    from guild import tabview
  File "/Users/bdorsey/anaconda3/lib/python3.6/site-packages/guild/tabview.py", line 18, in <module>
    import curses
  File "/Users/bdorsey/anaconda3/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: dlopen(/Users/bdorsey/anaconda3/lib/python3.6/lib-dynload/_curses.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libncursesw.5.dylib
  Referenced from: /Users/bdorsey/anaconda3/lib/python3.6/lib-dynload/_curses.cpython-36m-darwin.so
  Reason: image not found
`

**Comment by cfregly** [comment]
additional note:  i'm using Miniconda3 and i'm OK.

here is the missing library:
```
/Users/cfregly/miniconda3/lib/python3.6/lib-dynload/_curses.cpython-36m-darwin.so
```

(brent is using full Anaconda3 and he's having issues.)

**Comment by BrentDorsey** [comment]
The following steps resolved the "image not found" error:
* uninstall anaconda:  `rm -rf ~/.condarc ~/.conda ~/.continuum`
* `brew install ncurses`
* re-install anaconda

**Comment by gar1t** [comment]
I can't recreate this using Anaconda (conda 4.4.11) and Python 3.6.4.

@BrentDorsey can you import `curses` from the Python env this is showing up in?

Could you also post what you see from `guild check` here? That'll at least let us document the Python distro this is showing up in.

**Comment by gar1t** [comment]
I missed your update! Please disregard my previous post. Thanks for looking into this.
