### ISSUE TITLE
Error when View in TensorBoard clicked in Guild View

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#9]
Copied from #5:

```
`/anaconda3/lib/python3.6/site-packages/h5py/init.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/guild/commands/tensorboard_impl.py", line 106, in _load_guild_tensorboard_module
from guild import tensorboard
File "/anaconda3/lib/python3.6/site-packages/guild/tensorboard.py", line 51, in 
from tensorboard.plugins.audio import audio_plugin
File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in 
from tensorboard import plugin_util
File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugin_util.py", line 24, in 
import markdown
ModuleNotFoundError: No module named 'markdown'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/guild/scripts/guild", line 30, in 
main()
File "/anaconda3/lib/python3.6/site-packages/guild/scripts/guild", line 23, in main
guild.main_bootstrap.main()
File "/anaconda3/lib/python3.6/site-packages/guild/main_bootstrap.py", line 44, in main
guild.main.main()
File "/anaconda3/lib/python3.6/site-packages/guild/main.py", line 30, in main
_main()
File "/anaconda3/lib/python3.6/site-packages/guild/main.py", line 36, in _main
guild.commands.main.main(standalone_mode=False)
File "/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 731, in call
return self.main(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 706, in main
rv = self.invoke(ctx)
File "/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 1080, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 907, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/anaconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 544, in invoke
return callback(args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/guild/click_util.py", line 140, in fn
return fn0((args + (Args(kw),)))
File "/anaconda3/lib/python3.6/site-packages/guild/commands/tensorboard.py", line 74, in tensorboard
tensorboard_impl.main(args)
File "/anaconda3/lib/python3.6/site-packages/guild/commands/tensorboard_impl.py", line 86, in main
tensorboard = _load_guild_tensorboard_module()
File "/anaconda3/lib/python3.6/site-packages/guild/commands/tensorboard_impl.py", line 108, in _load_guild_tensorboard_module
_handle_tensorboard_import_error(e)
File "/anaconda3/lib/python3.6/site-packages/guild/commands/tensorboard_impl.py", line 113, in _handle_tensorboard_import_error
if e.message == 'No module named tensorflow':
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'`
```

**Comment by gar1t** [comment]
@BrentDorsey what do get when you run?

    guild check

**Comment by gar1t** [comment]
@BrentDorsey could you check this behavior in the latest pre release?

    pip install guildai --pre --upgrade

**Comment by BrentDorsey** [comment]
results of guild check:

```
$ guild check
guild_version:             0.3.0
guild_home:                /Users/bdorsey/.guild
guild_install_location:    /anaconda3/lib/python3.6/site-packages/guild
installed_plugins:         cloudml, cpu, disk, gpu, keras, memory
python_version:            3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
tensorflow_version:        1.6.0
tensorflow_cuda_support:   no
tensorflow_gpu_available:  no
tensorboard_version:       1.6.0
libcuda_version:           not loaded
libcudnn_version:          not loaded
nvidia_smi_version:        not installed
```

**Comment by BrentDorsey** [comment]
After executing `pip install guildai --pre --upgrade` and re-initializing `guild view` no longer opens and returns This site can’t be reached.  <machinename>.local refused to connect.

Steps to reproduce:
```
$ pip install guildai --pre --upgrade
Successfully installed guildai-0.3.1.dev1 python-dateutil-2.7.0 setuptools-38.5.2
$ guild init
You are about to initialize a Guild AI environment in /Users/bdorsey
Continue? (Y/n) Y
$ guild install mnist
Requirement already satisfied: gpkg.mnist in /Users/bdorsey/.local/lib/python3.6/site-packages
$ guild train mnist-softmax
You are about to run mnist/mnist-softmax:train
  batch-size: 100
  epochs: 10
Continue? (Y/n) Y
$ guild view
Running Guild View at http://BADMacPro.local:54470
$ guild check
guild_version:             0.3.1.dev1
guild_home:                /Users/bdorsey/.guild
guild_install_location:    /anaconda3/lib/python3.6/site-packages/guild
installed_plugins:         cloudml, cpu, disk, gpu, keras, memory
python_version:            3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
tensorflow_version:        1.6.0
tensorflow_cuda_support:   no
tensorflow_gpu_available:  no
tensorboard_version:       1.6.0
libcuda_version:           not loaded
libcudnn_version:          not loaded
nvidia_smi_version:        not installed
```

**Comment by gar1t** [comment]
@BrentDorsey What do you see when you run:

    tensorboard --logdir .

You don't need to open TensorBoard and can `CTRL-C` to shut that down - I'm just curious what it says for its URL.

**Comment by gar1t** [comment]
Also, to get around the startup problem, you can run:

    guild view --host localhost

This should at least open Guild View, where you can test the **View in TensorBoard** link.

**Comment by BrentDorsey** [comment]
```
$ tensorboard --logdir .
-bash: tensorboard: command not found
$ guild tensorboard --logdir .
guild: unrecognized option '--logdir'
Try 'guild tensorboard --help' for more information.
$ guild tensorboard
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TensorBoard could not be started: No module named 'markdown'
```

**Comment by BrentDorsey** [comment]
`guild view --host localhost` successfully opened the web app.
Selecting "VIEW IN TENSORBOARD" fails with:

Web page:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Bash:
```
$ guild view --host localhost
Running Guild View at http://localhost:49939
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/css/app.8222b0f062840a1a53144623b03b185e.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/js/manifest.c862daf62cbda66f38b3.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/js/vendor.60ca2345b9f42b35af52.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/js/app.3b32b317ce7bc4f9bbf4.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /config HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/fonts/MaterialIcons-Regular.570eb83.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:33] "GET /assets/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:34] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:34] "GET /assets/fonts/materialdesignicons-webfont.4b13596.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:39] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:44] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:50] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:03:56] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:04:02] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:04:08] "GET /runs HTTP/1.1" 200 -
127.0.0.1 - - [14/Mar/2018 11:04:11] "GET /tb/ HTTP/1.1" 303 -
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
127.0.0.1 - - [14/Mar/2018 11:04:12] "GET /tb/0/ HTTP/1.1" 500 -
ERROR: Error on request:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 337, in app
    return handler(*args, **kw)(env, start_resp)
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 383, in _handle_tb_index
    return tb_servers.start_server(key)
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 204, in start_server
    tensorboard = self._ensure_tensorboard()
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 216, in _ensure_tensorboard
    from guild import tensorboard
  File "/anaconda3/lib/python3.6/site-packages/guild/tensorboard.py", line 51, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugin_util.py", line 24, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
127.0.0.1 - - [14/Mar/2018 11:04:12] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2018 11:04:14] "GET /runs HTTP/1.1" 200 -
```

**Comment by gar1t** [comment]
There are two issues here:

1. Your hostname `BADMacPro.local` is likely not included in your `/etc/hosts` (or whatever Mac alternative uses), so clients won't be able to connect to web apps you run locally. I suspect `tensorboard` (Google's app, not the Guild command) will have the same problem. You can work around this by running these apps explicitly using `--host localhost`.

Btw, I ran across these instructions for modifying hosts (looks like the file is `/private/etc/hosts` in this doc):

https://www.tekrevue.com/tip/edit-hosts-file-mac-os-x/

2. TensorBoard is broken on your system. It should have been installed correctly when the `tensorflow` module was installed, including its program `tensorboard`. I see from `guild check` that it's finding tensorboard 1.6.0, which is what we'd expect. But the `markdown` package is missing, as is the `tensorboard` script.

Do you recall how TensorFlow was originally installed? Was it by way of `guild init` or did you install it another way?

I've created a Slack channel for troubleshooting, if you're comfortable with Slack. I sent an invite link to your gmail address.

**Comment by BrentDorsey** [comment]
I'm using a virtual environment so everything was installed via the [Quick start](https://www.guild.ai/) and guild init.

**Comment by BrentDorsey** [comment]
my host name is defined in /etc/hosts

**Comment by cfregly** [comment]
@gar1t :  can't you just default to "localhost" and change the host binding of TF TensorBoard/Guild View to '0.0.0.0'?

this works every time.

**Comment by gar1t** [comment]
@BrentDorsey could you install the latest pre-release by running:

    pip install  guildai --upgrade --pre

Let's see where things stand with that release.

**Comment by BrentDorsey** [comment]
blew away my virtual environment and started fresh.

```
$ pip install  guildai --upgrade --pre
Collecting guildai
  Downloading guildai-0.3.1.dev3-cp36-cp36m-macosx_10_12_x86_64.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 121kB/s
Collecting twine (from guildai)
  Downloading twine-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: Werkzeug in /anaconda3/lib/python3.6/site-packages (from guildai)
Collecting setuptools (from guildai)
  Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 178kB/s
Requirement already up-to-date: PyYAML in /anaconda3/lib/python3.6/site-packages (from guildai)
Collecting pip (from guildai)
  Downloading pip-9.0.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 47kB/s
Requirement already up-to-date: six in /anaconda3/lib/python3.6/site-packages (from guildai)
Requirement already up-to-date: Whoosh in /anaconda3/lib/python3.6/site-packages (from guildai)
Requirement already up-to-date: tabview in /anaconda3/lib/python3.6/site-packages (from guildai)
Requirement already up-to-date: chardet in /anaconda3/lib/python3.6/site-packages (from guildai)
Requirement already up-to-date: python-dateutil in /anaconda3/lib/python3.6/site-packages (from guildai)
Requirement already up-to-date: requests!=2.15,!=2.16,>=2.5.0 in /anaconda3/lib/python3.6/site-packages (from twine->guildai)
Collecting tqdm>=4.14 (from twine->guildai)
  Downloading tqdm-4.19.8-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 167kB/s
Collecting pkginfo>=1.4.2 (from twine->guildai)
  Downloading pkginfo-1.4.2-py2.py3-none-any.whl
Requirement already up-to-date: requests-toolbelt>=0.8.0 in /anaconda3/lib/python3.6/site-packages (from twine->guildai)
Requirement already up-to-date: idna<2.7,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai)
Requirement already up-to-date: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai)
Installing collected packages: tqdm, pkginfo, setuptools, twine, pip, guildai
  Found existing installation: tqdm 4.19.7
    Uninstalling tqdm-4.19.7:
      Successfully uninstalled tqdm-4.19.7
  Found existing installation: pkginfo 1.4.1
    Uninstalling pkginfo-1.4.1:
      Successfully uninstalled pkginfo-1.4.1
  Found existing installation: setuptools 38.5.2
    Uninstalling setuptools-38.5.2:
      Successfully uninstalled setuptools-38.5.2
  Found existing installation: twine 1.10.0
    Uninstalling twine-1.10.0:
      Successfully uninstalled twine-1.10.0
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: guildai 0.3.1.dev1
    Uninstalling guildai-0.3.1.dev1:
      Successfully uninstalled guildai-0.3.1.dev1
Successfully installed guildai-0.3.1.dev3 pip-9.0.2 pkginfo-1.4.2 setuptools-39.0.1 tqdm-4.19.8 twine-1.11.0

$ guild init
You are about to initialize a Guild AI environment in /Users/bdorsey
Continue? (Y/n) Y
Initialzing Guild environment in /Users/bdorsey
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TensorFlow version 1.6.0 installed
guild_version:             0.3.1.dev3
guild_home:                /Users/bdorsey/.guild
guild_install_location:    /anaconda3/lib/python3.6/site-packages/guild
installed_plugins:         cloudml, cpu, disk, gpu, keras, memory
python_version:            3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
tensorflow_version:        1.6.0
tensorflow_cuda_support:   no
tensorflow_gpu_available:  no
tensorboard_version:       1.6.0
libcuda_version:           not loaded
libcudnn_version:          not loaded
nvidia_smi_version:        not installed

$ guild install mnist
Requirement already satisfied: gpkg.mnist in /Users/bdorsey/.local/lib/python3.6/site-packages

$ guild train mnist-softmax
ERROR: unable to load models from /Users/bdorsey/.local/lib/python3.6/site-packages/gpkg/mnist/guild.yml: error in /Users/bdorsey/.local/lib/python3.6/site-packages/gpkg/mnist/guild.yml: missing required 'author-email' attribute in {'package': 'mnist', 'version': '0.3.0', 'description': 'CNN and softmax regression classifiers for MNIST digits', 'url': 'https://github.com/guildai/index/tree/master/mnist', 'maintainer': 'Guild AI', 'maintainer-email': 'packages@guild.ai', 'license': 'Apache 2.0', 'tags': ['mnist', 'cnn', 'softmax', 'images', 'model'], 'resources': {'dataset': {'description': "Yann Lecun's MNIST dataset in compressed IDX format", 'path': 'mnist-idx-data', 'sources': [{'url': 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz', 'sha256': '440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609'}, {'url': 'http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz', 'sha256': '3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c'}, {'url': 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz', 'sha256': '8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6'}, {'url': 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz', 'sha256': 'f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6'}]}}}
ERROR: error initializing 'mnist-cnn = guild.model:PackageModel' in gpkg.mnist 0.3.0
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/guild/entry_point_util.py", line 81, in for_name
    inst = res.inst()
  File "/anaconda3/lib/python3.6/site-packages/guild/entry_point_util.py", line 29, in inst
    self._inst = self._ep.resolve()(self._ep)
  File "/anaconda3/lib/python3.6/site-packages/guild/model.py", line 49, in __init__
    self.modeldef = self._init_modeldef()
  File "/anaconda3/lib/python3.6/site-packages/guild/model.py", line 121, in _init_modeldef
    "undefined model '%s' in %s" % (self.name, self.dist))
ValueError: undefined model 'mnist-cnn' in gpkg.mnist 0.3.0

$ guild check
guild_version:             0.3.1.dev3
guild_home:                /Users/bdorsey/.guild
guild_install_location:    /anaconda3/lib/python3.6/site-packages/guild
installed_plugins:         cloudml, cpu, disk, gpu, keras, memory
python_version:            3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
tensorflow_version:        1.6.0
tensorflow_cuda_support:   no
tensorflow_gpu_available:  no
tensorboard_version:       1.6.0
libcuda_version:           not loaded
libcudnn_version:          not loaded
nvidia_smi_version:        not installed

$ guild tensorboard
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TensorBoard could not be started: No module named 'markdown'
```

guild view works but the "View in TensorBoard" link is still raising a "ModuleNotFoundError: No module named 'markdown'" error.

```
$ guild view
Running Guild View at http://BADMacPro.local:57743
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR: Error on request:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/anaconda3/lib/python3.6/site-packages/guild/serving_util.py", line 93, in app
    return dispatch(routes, env, start_resp)
  File "/anaconda3/lib/python3.6/site-packages/guild/serving_util.py", line 82, in dispatch
    return handler(*args, **kw)(env, start_resp)
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 391, in _handle_tb_index
    return tb_servers.start_server(key)
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 225, in start_server
    tensorboard = self._ensure_tensorboard()
  File "/anaconda3/lib/python3.6/site-packages/guild/view.py", line 237, in _ensure_tensorboard
    from guild import tensorboard
  File "/anaconda3/lib/python3.6/site-packages/guild/tensorboard.py", line 51, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "/Users/bdorsey/.local/lib/python3.6/site-packages/tensorboard/plugin_util.py", line 24, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
```

**Comment by gar1t** [comment]
@BrentDorsey sorry I failed to mention - please use `--pre` when installing Guild packages (for now - there's a breaking change in the 0.3.1.dev release){

    guild install mnist --pre --upgrade

Use the `--pre --upgrade` dance when installing other Guild packages as well.

Regarding the TensorBoard issue, I'll spend some time with Anaconda to better understand it sets up environments and how pip interacts with them. One point of curiosity is that the Guild related modules are in what appears to be a privileged, non-environment/local location (`/anaconda3/lib/python3.6/site-packages`) whereas the tensorboard module is local (`/Users/bdorsey/.local/lib/python3.6/site-packages`).

I suspect the culprit here is the way Guild is installing tensorflow (which in turn installs tensorboard)!

One simple test you could make is repeat the install process as before, but use `--no-check` when running `init`:

    guild init --no-check

You'll then need to install the `tensorflow` package manually.

You want to get to the point where tensorboard works without Guild. So running this works without errors:

    tensorboard --logdir .

**Comment by BrentDorsey** [comment]
I would suggest defining tesorflow and tensorboard as dependencies in requirements.txt so they're installed by the PIP package manager then have guild customize the config.

**Comment by gar1t** [comment]
I'd love to! The problem is that tensorflow is shipped in two packages and pip doesn't know which package to install. If Guild included tensorflow as a dep, installing it would break environments that used the other package.

`guild init` checks if you have a GPU and tees up the correct package to install. That's the reason it goes through all that trouble.

**Comment by gar1t** [comment]
I'm currently in the process of setting up some CI tests that cover the use of conda. Our current coverage on MacOS 3.6 uses virtualenv that's provided with the Python 3.6 package from Homebrew.

It shouldn't be hard for `guild init` to get the installation right for the conda environments.

In the meantime, you can install tensorboard directly as package. It doesn't have to be installed by way of `guild init` - that's just a convenience (though in this case, it appears to be not-so-convenient!)

**Comment by gar1t** [comment]
@BrentDorsey, @cfregly could you please install 0.3.1.dev6 or later:

    pip install guildai --pre --upgrade

I expect this release will resolve the two problems raised in this issue:

- Incorrect interface binding and hostname used for View (host not found when running View)
- Errors generated when viewing issues in TensorBoard

Let me know if you are still seeing problems. I'll keep this open until I hear back. Thanks!
