### ISSUE TITLE
Permission denied when running - guild check

### ISSUE THREAD

**Issue by pgirardgerad** [guildai/guildai#92]
Hello,
  after installing guildai with pip, the check fails because guild is trying to write to a directory outside of my user account. The python used is outside of my account and not writable by myself.

Here's a quick traceback of the error.

./guild check
Traceback (most recent call last):
  File "./guild", line 8, in <module>
    sys.exit(main())
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/main_bootstrap.py", line 38, in main
    guild.main.main()
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/main.py", line 32, in main
    _main()
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/main.py", line 38, in _main
    main_cmd.main(standalone_mode=False)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/external/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/external/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/external/click/core.py", line 1129, in invoke
    Command.invoke(self, ctx)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/external/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/external/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/click_util.py", line 146, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/commands/main.py", line 99, in main
    main_impl.main(args)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/commands/main_impl.py", line 29, in main
    config.set_guild_home(_guild_home(args))
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/commands/main_impl.py", line 40, in _guild_home
    return _validated_dir(args.guild_home, abs=True, create=True)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/commands/main_impl.py", line 48, in _validated_dir
    util.ensure_dir(path)
  File "/home/pierreg/.local/lib/python3.7/site-packages/guild/util.py", line 65, in ensure_dir
    os.makedirs(d)
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-2019.07/envs/pytorch-1.3.0/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/x86_64-unknown-linux_ol7-gnu/anaconda-2019.07/envs/pytorch-1.3.0/.guil
d'

To workaround this, it was suggested I define my GUILD_HOME to a directory where I can write and that solved the issue.

**Comment by gar1t** [comment]
Thank you! Marking as bug as Guild needs to handle this gracefully with a helpful message about using `GUILD_HOME` to define an alternative location.

**Comment by pgirardgerad** [comment]
Unless there's something special going on, why not put it in $HOME/.guild by default? That should be writable most of the time.

**Comment by gar1t** [comment]
That's the default when not running in a virtual env. Guild makes the assumption that by running in a virtual env, you want to isolate your runs along with your project code.

**Comment by gar1t** [comment]
Looking into this more, Guild takes a very Erlangish approach to the problem of IO error - let it crash! It does a bit of proactive work up front in creating the Guild home if it doesn't exist. But this is weak. Not only is Guild modifying the system on read-only ops (e.g. `check`, `runs list`, etc.) it doesn't really have any idea what sort of permissions it needs within that hierarchy.

We need to keep this issue open as a general placeholder to gracefully and correctly handle these sorts of errors.
