### ISSUE TITLE
guild tensorboard with true/false flags

### ISSUE THREAD

**Issue by dvirginz** [guildai/guildai#99]
When having flags set to true/false, TensorFlow seems to fail to open, having a `500 SERVER ERROR`.
The full error
```
ERROR: Error on request:
Traceback (most recent call last):
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 371, in _handle_tb
    return tb_servers[key]
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 202, in __getitem__
    return self._servers[key]
KeyError: '0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 361, in _handle_tb_index
    return _handle_tb(req, tb_servers, key)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 373, in _handle_tb
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/serving_util.py", line 118, in app
    return dispatch(routes, env, start_resp)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/serving_util.py", line 107, in dispatch
    return handler(*args, **kw)(env, start_resp)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 366, in _handle_tb_index
    return tb_servers.start_server(key)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 208, in start_server
    server.start()
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/view.py", line 155, in start
    self._monitor.run_once(exit_on_error=True)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/run_util.py", line 74, in run_once
    self._refresh_logdir(runs)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/run_util.py", line 82, in _refresh_logdir
    self.refresh_run_cb(run, path)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 146, in f
    return _refresh_run(run, run_logdir, state)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 150, in _refresh_run
    _refresh_tfevent_links(run, run_logdir, state)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 158, in _refresh_tfevent_links
    _init_tfevent_link(tfevent_path, link, run, state)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 173, in _init_tfevent_link
    _init_hparam_session(run, link_dir, state)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 179, in _init_hparam_session
    _add_hparam_experiment(state.hparam_experiment, writer)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/tensorboard.py", line 187, in _add_hparam_experiment
    writer.add_hparam_experiment(hparams, metrics)
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/summary.py", line 116, in add_hparam_experiment
    self._add_summary(_HParamExperiment(hparams, metrics))
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/summary.py", line 158, in _HParamExperiment
    hparams=[_HParam(key, vals) for key, vals in hparams.items()],
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/summary.py", line 158, in <listcomp>
    hparams=[_HParam(key, vals) for key, vals in hparams.items()],
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/guild/summary.py", line 170, in _HParam
    return hp.HParam(name, hp.Discrete(legal_vals))
  File "/home/dvir/anaconda3/envs/unetgan3d/lib/python3.6/site-packages/tensorboard/plugins/hparams/summary_v2.py", line 488, in __init__
    % (value, self._dtype.__name__)
TypeError: dtype mismatch: not isinstance('False', bool)
```

The current fix:

Using Garret's tip:
Switch to False->0 True->1 and deleting all the previous experiments fixed it.

**Comment by gar1t** [comment]
I'm having a hard time reproducing this. Could you provide the following details?

- Version of Guild and TensorBoard (use `guild check` to get both)
- Applicable operation def (from your Guild file / `guild.yml`)
- If the flag is implemented as a global, what's it's default value in Python - if it's implemented as a cmd line arg, what's it's default in the parser def?
- Command you're running that generates one of the problematic runs

Thanks!

**Comment by gar1t** [comment]
I created an issue resolution project to help on the recreation front:

https://github.com/guildai/issue-resolution/tree/master/99-guild-tensorboard-with-true-false-flags

If there's something there that you can adjust to recreate the problem I can merge a PR. Otherwise I'll keep working on it based on your feedback here.

**Comment by gar1t** [comment]
This looks fixed to me in 0.7.0 based on the resolution doc. If you feel otherwise please re-open. Thanks for the report!

**Comment by eric-mitchell** [comment]
**Edit:**

**Turns out this was just because I had too new of a tensorboard version accidentally installed. I'll leave my comment in case it's still useful for you.**

Hey Garrett,

I'm still having this issue with 0.7.0. For me, it comes up when I use argparse. Minimal repro:

```
###########
# test.py # 
###########

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--test', action='store_true')
args = parser.parse_args()

print(args)
```
```
#############
# guild.yml # 
#############

test:
  main: test
  flags-import: all
```
Error message is:

```
ERROR: Error on request:
Traceback (most recent call last):
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 394, in _handle_tb
    return tb_servers[key]
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 207, in __getitem__
    return self._servers[key]
KeyError: '0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 383, in _handle_tb_index
    return _handle_tb(req, tb_servers, key)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 396, in _handle_tb
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/serving_util.py", line 124, in app
    return dispatch(routes, env, start_resp)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/serving_util.py", line 113, in dispatch
    return handler(*args, **kw)(env, start_resp)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 388, in _handle_tb_index
    return tb_servers.start_server(key)
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 213, in start_server
    server.start()
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/view.py", line 164, in start
    disabled_plugins=TB_DISABLED_PLUGINS,
  File "/juice/u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild/tensorboard.py", line 525, in create_app
    return application.standard_tensorboard_wsgi(
AttributeError: module 'tensorboard.backend.application' has no attribute 'standard_tensorboard_wsgi'
```

`guild check` shows

```
guild_version:             0.7.0.post1
guild_install_location:    /u/nlp/anaconda/main/anaconda3/envs/py37-eric/lib/python3.7/site-packages/guild
guild_home:                /juice/scr/em7/separate_knowledge/.guild
guild_resource_cache:      /juice/scr/em7/separate_knowledge/.guild/cache/resources
installed_plugins:         cpu, disk, exec_script, gpu, keras, memory, perf, python_script, queue, skopt
python_version:            3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
python_exe:                /u/nlp/anaconda/main/anaconda3/envs/py37-eric/bin/python
platform:                  Linux 4.4.0-130-generic x86_64
psutil_version:            5.6.3
tensorboard_version:       2.4.0
cuda_version:              10.0.130
nvidia_smi_version:        ERROR: b'No devices were found'
latest_guild_version:      0.7.0.post1
```

**Comment by gar1t** [comment]
Thank you! Guild 0.7.1 does support TensorBoard 2.4. You can try it by installing the current pre-release version.

    pip install guildai --upgrade --pre

You should be able to install the latest TensorBoard version and run this scenario successfully.

**Comment by eric-mitchell** [comment]
Awesome- will give this a try! Thanks for your amazing work on Guild, really enjoying it so far.
